version: 2.1

jobs:
  backend-build-and-deploy:
    docker:
      - image: circleci/node:16  # Use a Node.js Docker image
    steps:
      - checkout  # Pull the latest code
      
      # Install dependencies
      - run:
          name: Install Dependencies
          working_directory: ./backend
          command: npm install

      # Test the application (optional)
      - run:
          name: Test Application
          working_directory: ./backend
          command: echo 'abc'  # Use if you have test scripts, or remove this step

      # Deploy to AWS EC2
      - run:
          name: Deploy to AWS EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@100.27.212.246 \<<EOF
              cd /var/www/backend
              git pull origin main
              npm install
              npm run start
            EOF

workflows:
  build-and-deploy:
    jobs:
      - backend-build-and-deploy

